name: Cross compile

on:
  push:
    tags:
      - 'socks*'
  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  releases-matrix:
    name: Cross compile

    runs-on: ubuntu-20.04

    steps:
      - name: Git clone
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 1

      - name: xgo build
        uses: crazy-max/ghaction-xgo@v3.0.0
        with:
          xgo_version: latest
          go_version: 1.21
          dest: dist
          prefix: socks5
          targets: linux/amd64,linux/arm64,linux/arm-7,linux/s390x,linux/riscv64,linux/386
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default

      - name: Release binary files
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: socks5
          files: dist/*.tar.gz
