name: Cross compile

on:
  push:
    branches:
      - '*'
    tags:
      - 'socks*'
  workflow_dispatch:


jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
      BINARY: socks5

    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    
    steps:
      - name: Git clone repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 1

      - uses: wangyoucao577/go-release-action@v1.41
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "1.21.5"
          project_path: "go"
          ldflags: -s -w --extldflags '-static -fpic'
          md5sum: "FALSE"
          release_tag: "${{ env.BINARY }}"
          release_name: "${{ env.BINARY }}"
          binary_name: "${{ env.BINARY }}"
          compress_assets: "AUTO"
          asset_name: "${{ env.BINARY }}-${{ matrix.goos }}-${{ matrix.goarch }}"

      - name: Delete old workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repository: ${{ github.repository }}
          older-than-seconds: 3600
