name: Cross compile

on:
  push:
    branches:
      - main
    tags:
      - 'socks*'
  workflow_dispatch:

jobs:
  releases-matrix:
    name: Cross compile

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      
      - name: xgo build
        uses: crazy-max/ghaction-xgo@v3.0.0
        with:
          xgo_version: latest
          go_version: 1.21
          dest: dist
          pkg: go
          prefix: socks5
          targets: linux/amd64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default

      - name: Release binary files
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: socks5
          files: dist/*.tar.gz
